// <auto-generated />
using Earthquake.Emergency.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Earthquake.Emergency.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230529151211_UserModelChanges")]
    partial class UserModelChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Earthquake.Emergency.Domain.Entities.Emergency.EmergencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Latidute")
                        .HasColumnType("real");

                    b.Property<float>("Longidute")
                        .HasColumnType("real");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Emergencies");
                });

            modelBuilder.Entity("Earthquake.Emergency.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Earthquake.Emergency.Domain.Entities.Emergency.EmergencyEntity", b =>
                {
                    b.HasOne("Earthquake.Emergency.Domain.Entities.User.UserEntity", "User")
                        .WithOne("Emergency")
                        .HasForeignKey("Earthquake.Emergency.Domain.Entities.Emergency.EmergencyEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Earthquake.Emergency.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Emergency")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
